CREATE TABLE USER(
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    NUME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PAROLA VARCHAR(255) NOT NULL,
    TIP_USER ENUM('USER','TRAINER','ADMIN') NOT NULL
);

CREATE TABLE SESSION(
    ID_USER INT,
    ID_SESSION VARCHAR(255),
    PRIMARY KEY(ID_USER,ID_SESSION),
    FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER)
);

CREATE TABLE ABONAMENT(
    ID_ABONAMENT INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    DATA_START DATE NOT NULL,
    DATA_FINALIZARE DATE NOT NULL,
    NUMAR_SEDINTE INT
);

