CREATE TABLE users(
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PAROLA VARCHAR(255) NOT NULL,
    TIP_USER ENUM('USER','TRAINER','ADMIN') NOT NULL
);

CREATE TABLE sessions(
    ID_USER INT,
    ID_SESSION VARCHAR(255),
    PRIMARY KEY(ID_USER,ID_SESSION),
    FOREIGN KEY(ID_USER) REFERENCES users(ID_USER)
);

CREATE TABLE abonaments(
    ID_ABONAMENT INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    DATA_START DATE NOT NULL,
    DATA_FINALIZARE DATE NOT NULL,
    NUMAR_SEDINTE INT
);

ALTER TABLE users
ADD COLUMN antrenor_id INTEGER DEFAULT NULL;


ALTER TABLE users
ADD CONSTRAINT fk_antrenor
FOREIGN KEY (antrenor_id) REFERENCES users(id_user);

