INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (1, 'Genuflexiuni');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (2, 'Flotări');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (3, 'Tracțiuni');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (4, 'Fandări');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (5, 'Plank');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (6, 'Îndreptări');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (7, 'Ramat cu gantere');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (8, 'Presă pentru umeri');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (9, 'Abdomene');
INSERT INTO EXERCITII (id_exercitiu, denumire) VALUES (10, 'Sărituri la coardă');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (1, 'Forță');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (2, 'Cardio');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (3, 'Flexibilitate');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (4, 'HIIT');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (5, 'Yoga');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (6, 'Pilates');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (7, 'CrossFit');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (8, 'Culturism');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (9, 'Reabilitare');
INSERT INTO TIP_ANTRENAMENT (id_tip, denumire) VALUES (10, 'Sport de echipă');