INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (1, 'Lactate');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (2, 'Gluten');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (3, 'Arahide');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (4, 'Fructe de mare');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (5, 'Soia');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (6, 'Nuci');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (7, 'Ouă');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (8, 'Pește');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (9, 'Semințe de susan');
INSERT INTO ALERGENI (id_alergeni, denumire) VALUES (10, 'Sulfiti');
INSERT INTO DIETA (id_dieta, denumire) VALUES (1, 'Vegetarian');
INSERT INTO DIETA (id_dieta, denumire) VALUES (2, 'Vegan');
INSERT INTO DIETA (id_dieta, denumire) VALUES (3, 'Keto');
INSERT INTO DIETA (id_dieta, denumire) VALUES (4, 'Low Carb');
INSERT INTO DIETA (id_dieta, denumire) VALUES (5, 'Mediterranean');