CREATE TABLE users(
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PAROLA VARCHAR(255) NOT NULL,
    TIP_USER ENUM('USER','TRAINER','ADMIN') NOT NULL
);

CREATE TABLE sessions(
    ID_USER INT,
    ID_SESSION VARCHAR(255),
    PRIMARY KEY(ID_USER,ID_SESSION),
    FOREIGN KEY(ID_USER) REFERENCES users(ID_USER)
);

CREATE TABLE abonaments(
    ID_ABONAMENT INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    DATA_START DATE NOT NULL,
    DATA_FINALIZARE DATE NOT NULL,
    NUMAR_SEDINTE INT
);

ALTER TABLE users
ADD COLUMN antrenor_id INTEGER DEFAULT NULL;


ALTER TABLE users
ADD CONSTRAINT fk_antrenor
FOREIGN KEY (antrenor_id) REFERENCES users(id_user);

ALTER TABLE abonaments
ADD COLUMN TIP_ABONAMENT VARCHAR(20) NOT NULL DEFAULT 'standard';

CREATE TABLE notificari (
    ID_NOTIFICARE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INTEGER NOT NULL,
    MESAJ TEXT NOT NULL,
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CITIT BOOLEAN DEFAULT FALSE
);

ALTER TABLE notificari ADD COLUMN TIP VARCHAR(20) DEFAULT 'generala';

CREATE TABLE polls (
    ID_POLL INT AUTO_INCREMENT PRIMARY KEY,
    ID_TRAINER INT NOT NULL,
    ACTIV BOOLEAN NOT NULL DEFAULT TRUE,
    DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_TRAINER) REFERENCES users(ID_USER)
);
CREATE TABLE votes (
    ID_VOTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_POLL INT NOT NULL,
    ID_USER INT NOT NULL,
    ORA INT NOT NULL,
    DATA_VOT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_POLL) REFERENCES polls(ID_POLL),
    FOREIGN KEY (ID_USER) REFERENCES users(ID_USER),
    UNIQUE (ID_POLL, ID_USER)
);
CREATE TABLE conversations (
    ID_CONVERSATION INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    ID_TRAINER INT NOT NULL,
    DATA_START DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USER) REFERENCES users(ID_USER),
    FOREIGN KEY (ID_TRAINER) REFERENCES users(ID_USER)
);
CREATE TABLE messages (
    ID_MESSAGE INT PRIMARY KEY AUTO_INCREMENT,
    ID_CONVERSATION INT NOT NULL,
    ID_SENDER INT NOT NULL,
    MESAJ TEXT NOT NULL,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CONVERSATION) REFERENCES conversations(ID_CONVERSATION),
    FOREIGN KEY (ID_SENDER) REFERENCES users(ID_USER)
);
ALTER TABLE messages
ADD COLUMN VAZUT BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE ALIMENT (
    id_aliment INT PRIMARY KEY,
    nume TEXT,
    calorii FLOAT,
    proteine FLOAT,
    carbohidrati FLOAT,
    zaharuri FLOAT,
    grasimi_saturate FLOAT,
    grasimi_nesaturate FLOAT,
    fibre FLOAT
);
CREATE TABLE jurnal_alimentar (
    ID_JURNAL_ALIMENTAR INT PRIMARY KEY AUTO_INCREMENT, -- Or SERIAL for PostgreSQL, etc.
    ID_USER INT NOT NULL,
    ID_ALIMENT INT NOT NULL,
    TIP_MASA VARCHAR(50) NOT NULL,
    CANTITATE INT NOT NULL,
    DATA_ADAUGARE DATE NOT NULL,
    -- Foreign key constraints
    FOREIGN KEY (ID_USER) REFERENCES users(ID_USER), -- Assuming your users table is named 'users' and has an ID_USER primary key
    FOREIGN KEY (ID_ALIMENT) REFERENCES aliment(ID_ALIMENT)
);
